### ISSUE TITLE
provider_ignores_state: true possible

### ISSUE THREAD

**Issue by antoineherzog** [isaacsanders/omniauth-stripe-connect#34]
Hi!
I noticed that if the user is edit several times the stripe page we can get

Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected

How should we handle this case ?

Kind regards,
Antoine

**Comment by isaacsanders** [comment]
What version of the gem are you working with?

**Comment by bolom** [comment]
@isaacsanders i have got the same issue

**Comment by isaacsanders** [comment]
What version of the gem are you using? I believe that this is fixed in the most recent version.

**Comment by mgraulich** [comment]
@isaacsanders I'm using 2.7.0 and getting the same error.

**Comment by isaacsanders** [comment]
Okay. Anyone online to work with me on this? I am ready to devote some hours to this, but I will need someone to help me understand the problem more.

**Comment by mgraulich** [comment]
I had to update back up to 2.7.0... When i rolled back to 2.6.0 I started seeing the csrf_detected issue with my facebook oAuth flow. I didn't have this issue until i updated rails from 4.0.5 to 4.1.10.  I currently have facebook and stripe_connect declared in my omniauth.rb initializer (i'm not using the devise flow). I had to add the provider_ignores_state to the initializer to get everything to work together on 4.1.10.

**Comment by isaacsanders** [comment]
So, the Stripe security people contacted me to remove the provider_ignores_state option. I imagine it is important to them that it doesn't ignore state. I don't know why it would break things.

I will try to loop in my contact on this.

**Comment by mgraulich** [comment]
Sounds good. Yeah, it's kind of strange. I was passing in a state param (https://stripe.com/docs/connect/reference) but it was still failing when i removed that.

**Comment by isaacsanders** [comment]
@antoineherzog @bolom @mgraulich 

Hey. I just found a bug in omniauth-oauth2 that might have been the cause of this bug. I am so sorry it has taken this long to get this resolved. I hope that a new version of omniauth-oauth2 will come out soon with my fix in it, then I will release another version of this gem, hopefully fixing all of your problems.

Thank you for your patience.

– Isaac

**Comment by isaacsanders** [comment]
@antoineherzog @bolom @mgraulich 

Just released v2.8.0.

Please tell me if the issue persists. We can reopen from there.

**Comment by turbodiesel3** [comment]
I have also gotten this issue with the latest version:

 E, [2015-07-25T22:29:12.253165 #30793] ERROR -- omniauth: (stripe_connect) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected

What i ended up doing is downgrading to 2.6.0 and removing everything from omniauth.rb, and the account creation went through.

**Comment by isaacsanders** [comment]
I have just run through the login flow with out the provider_ignores_state parameter using https://github.com/PracticallyGreen/omniauth-test-harness

I had no issues on 2.8.0. Please try to recreate the error using the test harness mentioned above.

Thanks for your help in fixing this issue.

**Comment by isaacsanders** [comment]
Realized that Stripe might have misunderstood this parameter's purpose. Adding it back in and telling the Stripe folks.

**Comment by isaacsanders** [comment]
Version 2.9.0 going out today. Let me know if this works for you.
