### ISSUE TITLE
Pass params through to callback

### ISSUE THREAD

**Issue by humansounds** [isaacsanders/omniauth-stripe-connect#36]
I need to pass a param in the initial authorization url that will get passed through to the callback.  Right now, I am simply hijacking the `status` param, as it gets returned by default in the callback url.  Any advice on how to achieve this?

**Comment by humansounds** [comment]
As a side note, I am getting nothing back in `request.env["omniauth.origin"]` or `request.env["omniauth.params"]`.

**Comment by isaacsanders** [comment]
check out the `state` param in v2.9.0.

**Comment by humansounds** [comment]
I ended up switching to Managed Stripe accounts instead of Standalone via Connect.  Closing this for now.  Thanks.
