### ISSUE TITLE
Uploaded Stripe app to Heroku now i get error omniauth: (stripe_connect) Authentication failure! invalid_credentials: OAuth2::Error, invalid_client: No such API key: Bearer

### ISSUE THREAD

**Issue by farhansyed9** [isaacsanders/omniauth-stripe-connect#37]
i tested my app locally and works fine, but then i deployed it to Heroku and no im running into issues. 
i get this error after i skip the form for redirection:
 ERROR -- omniauth: (stripe_connect) Authentication failure! invalid_credentials: OAuth2::Error, `<invalid_client: No such API key: Bearer
2015-08-14T07:37:34.345409+00:00 app[web.1]: {
2015-08-14T07:37:34.345425+00:00 app[web.1]:   "error": "invalid_client",
2015-08-14T07:37:34.345427+00:00 app[web.1]:   "error_description": "No such API key: Bearer">`

This is what my files look like 

using gem figaro for handling the keys. 

application.yml: 
`<STRIPE_SECRET: sk_test_***************
STRIPE_CONNECT_CLIENT_ID: ca_**************>`

omniauth.rb: 

`<Rails.application.config.middleware.use OmniAuth::Builder do
  provider :stripe_connect, ENV['STRIPE_CONNECT_CLIENT_ID'], ENV['STRIPE_SECRET']
end>`

secrets.yml:
`<STRIPE_SECRET: sk_test_***************
STRIPE_CONNECT_CLIENT_ID: ca_**************>`

**Comment by johnshencanada** [comment]
Weird I have the same error!
Everything works in development but not in production

**Comment by lskd** [comment]
@farhansyed9 @johnshencanada , did you guys get this to work out? 
Sounds like this error code :  "API key mode (live or test mode) does not match the client_id mode." found at the bottom here : https://stripe.com/docs/connect/reference#post-deauthorize-error-codes

**Comment by farhansyed9** [comment]
Yeah I actually was using wrong api keys, so I just deauthorized all keys
and got new ones and it worked.

**Comment by lskd** [comment]
@farhansyed9  awesome, thanks for the followup

**Comment by farhansyed9** [comment]
No problem, let me know if you have any other issues.
