### ISSUE TITLE
Documentation is nearly useless unless you intend to use Devise

### ISSUE THREAD

**Issue by rlugge** [isaacsanders/omniauth-stripe-connect#40]
The documentation for this gem so heavily relies on the use of Devise that you might as well add devise as a requirement for it's use.  Which is unfortunate, as Devise is an over-used gem that doesn't work well in many use cases.  For example, in my use case I'm not interested in using oauth for user registration / login purposes, I simply need to connect the users Stripe account to my application.  Devise -- which is being used for those purposes -- not only doesn't need to be involved in this work flow, it needs to be kept as far as possible from it!

**Comment by amritk** [comment]
+1

**Comment by isaacsanders** [comment]
I am always happy to read and merge in Pull Requests. I don't use this professionally anymore, so if you would get value out of better docs and get paid to write this code, please get paid to contribute.

If you can't take the time to do that, I recommend you read the OmniAuth docs, they have generally been helpful for me.

**Comment by isaacsanders** [comment]
If you read the README for https://github.com/intridea/omniauth, you can figure it out in the first couple sections.
