### ISSUE TITLE
upgrade from 2.9.0 to 2.10.0 leads to `invalid_redirect_uri` error

### ISSUE THREAD

**Issue by srt32** [isaacsanders/omniauth-stripe-connect#48]
We recently upgraded from 2.9.0 to [2.10.0](https://github.com/isaacsanders/omniauth-stripe-connect/releases/tag/v2.10.0). Upon upgrading we experienced the below `invalid_redirect_uri` error that we did not see before the upgrade. 

This version bump seems to only bump transitive dependencies. Is there any updated config needed to make the new version work properly?

```
{
  "error": "invalid_redirect_uri",
  "error_description": "Invalid redirect URI 'https://mydomain.com/callback'. Ensure this uri exactly matches one of the uris specified in your application settings",
  "state": "state-field-foo"
}
```

Thanks!

**Comment by ryanclark2** [comment]
We did some research and found that overriding the `callback_url` url in our strategy in our initializer and excluding the `query_string` made this work. It would be nice not to have to do that. 

Related issue: https://github.com/intridea/omniauth-oauth2/issues/93#issuecomment-257319242

🌞

**Comment by isaacsanders** [comment]
@srt32 @ryanclark2 @chrt00 PR #47 has the relevant method, but it is buried under adding the use of a JWT to the gem.

I would be happy to merge a PR with just the `callback_url` method defined.

**Comment by ryanclark2** [comment]
@isaacsanders Yup, that's exactly what we did. If you'd like a PR with just that in it, let me know.

**Comment by isaacsanders** [comment]
I'm into it.

**Comment by isaacsanders** [comment]
As in, yes, I would like a PR, and will merge it in/cut a release.

**Comment by ryanclark2** [comment]
Ha, I caught your drift. I'll send it over it a short bit. Thanks.

**Comment by isaacsanders** [comment]
Version 2.10.1 released

**Comment by isaacsanders** [comment]
@srt32 @ryanclark2 If either of you two are still working on this, I would appreciate it if you would confirm that 2.10.1 fixes the issue for you.
