### ISSUE TITLE
cannot upgrade Faraday due to omniauth-stripe-connect dependancies 

### ISSUE THREAD

**Issue by RSR312-206** [isaacsanders/omniauth-stripe-connect#58]
I need to upgrade Faraday from 0.12.2 to the most recent stable version: 0.17.1

When I try to update my Gemfile, I'm getting blocked because `omiauth-stripe-connect` has a version limit from a couple downstream dependencies:

```
 omniauth-stripe-connect was resolved to 2.10.1, which depends on
      omniauth-oauth2 (~> 1.4) was resolved to 1.5.0, which depends on
        oauth2 (~> 1.1) was resolved to 1.4.0, which depends on
          faraday (>= 0.8, < 0.13)

```

`omniauto-oauth2` is on 1.6.0
`oauth2` has a new version with a [relaxed Faraday dependency](https://github.com/oauth-xx/oauth2/blob/master/oauth2.gemspec). 

Can you please update your dependencies so we can move past Faraday version 0.13?

**Comment by isaacsanders** [comment]
@RSR312-206 hey! This isn’t something I use for my day job, so if you wanna make a PR, I would appreciate it.
